"""Helpers for authoring and managing Software Hub custom cards.

This module wraps the Software Hub (Zen) Custom cards API:

    GET    /zen-data/v1/custom_cards          - list custom cards
    PUT    /zen-data/v1/custom_cards/{key}    - create or replace a card
    PATCH  /zen-data/v1/custom_cards/{key}    - update an existing card
    DELETE /zen-data/v1/custom_cards/{key}    - delete a card

Authentication uses a Zen API key authorization header generated by
``generate_zen_auth_header`` from ``auth_helper_functions``. The acting user
must have administration privileges in Software Hub.
"""

import requests

from auth_helper_functions import generate_zen_auth_header


# Allowed template_type values per the Custom cards API.
VALID_TEMPLATE_TYPES = (
    "bar",
    "big_number",
    "content_block",
    "donut",
    "list",
    "number_list",
    "text_list",
)


class SoftwareHubCustomCardError(Exception):
    """Raised when the Custom cards API returns an error response."""

    def __init__(self, message, status_code=None, response=None):
        super().__init__(message)
        self.status_code = status_code
        self.response = response


class SoftwareHubCustomCardManager:
    """Authors and manages Software Hub custom cards via the Zen API.

    Example:
        manager = SoftwareHubCustomCardManager(
            cpd_cluster_host="https://cpd.example.com",
            username="admin",
            api_key="...",
        )
        manager.create_or_replace_card(
            key="disk_usage",
            permissions=["manage_catalog"],
            order=1,
            title="Disk usage",
            template_type="big_number",
            data={
                "big_number_data": {
                    "metric": "55",
                    "sub_text": "Increase since last month",
                    "suffix": "%",
                }
            },
        )
    """

    API_PATH = "/zen-data/v1/custom_cards"

    def __init__(self, cpd_cluster_host, username, api_key, verify=True, timeout=30):
        """Initialize the manager.

        Args:
            cpd_cluster_host: Base URL of the CPD/Software Hub cluster,
                e.g. "https://cpd.example.com". A scheme is added if missing.
            username: Zen username with administration privileges.
            api_key: Zen API key for the user.
            verify: TLS verification. True (default), False to skip, or a path
                to a CA bundle. Passed through to ``requests``.
            timeout: Per-request timeout in seconds.
        """
        if not cpd_cluster_host:
            raise ValueError("cpd_cluster_host is required")

        if not cpd_cluster_host.startswith(("http://", "https://")):
            cpd_cluster_host = f"https://{cpd_cluster_host}"

        self.cpd_cluster_host = cpd_cluster_host.rstrip("/")
        self.verify = verify
        self.timeout = timeout
        self._auth_header = generate_zen_auth_header(username, api_key)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _url(self, key=None):
        """Build the API URL, optionally for a specific card key."""
        url = f"{self.cpd_cluster_host}{self.API_PATH}"
        if key:
            url = f"{url}/{key}"
        return url

    def _headers(self):
        """Standard headers for every request."""
        return {
            "Authorization": self._auth_header,
            "Accept": "application/json",
            "Accept-Language": "en-US",
            "Content-Type": "application/json",
        }

    def _request(self, method, key=None, json_body=None):
        """Issue a request and return the parsed JSON body.

        Raises:
            SoftwareHubCustomCardError: For non-2xx responses.
        """
        response = requests.request(
            method,
            self._url(key),
            headers=self._headers(),
            json=json_body,
            verify=self.verify,
            timeout=self.timeout,
        )

        if not response.ok:
            raise SoftwareHubCustomCardError(
                f"{method} {self._url(key)} failed with status "
                f"{response.status_code}: {response.text}",
                status_code=response.status_code,
                response=response,
            )

        # DELETE and some responses may carry an empty body.
        if not response.content:
            return {}
        try:
            return response.json()
        except ValueError:
            return {"raw": response.text}

    @staticmethod
    def _validate_card_fields(
        order=None, title=None, template_type=None, description=None
    ):
        """Validate common card field constraints from the API spec."""
        if order is not None and not (1 <= int(order) <= 50):
            raise ValueError("order must be in the range 1 - 50")

        if title is not None and len(title) > 40:
            raise ValueError("title must be 40 characters or less")

        if template_type is not None and template_type not in VALID_TEMPLATE_TYPES:
            raise ValueError(
                f"template_type must be one of {VALID_TEMPLATE_TYPES}, "
                f"got '{template_type}'"
            )

        if description is not None and len(description) > 200:
            raise ValueError("description must be 200 characters or less")

    @staticmethod
    def _prune(payload):
        """Drop keys whose value is None so optional fields are omitted."""
        return {k: v for k, v in payload.items() if v is not None}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def list_cards(self):
        """Retrieve the properties of custom cards that you can update.

        GET /zen-data/v1/custom_cards

        Returns:
            dict: The parsed API response (includes ``data``).
        """
        return self._request("GET", key=None)

    def create_or_replace_card(
        self,
        key,
        permissions,
        order,
        title,
        template_type,
        data=None,
        data_url=None,
        roles=None,
        drilldown_url=None,
        description=None,
        service_defined_id=None,
        window_open_target=None,
        refresh_rate=None,
    ):
        """Create a custom card or replace an existing one.

        PUT /zen-data/v1/custom_cards/{key}

        Args:
            key: Unique name of the card. Created if absent, replaced if present.
            permissions: List of permissions a user needs to see the card.
                Must contain at least one permission.
            order: Card position, 1 - 50.
            title: Display name, 40 characters or less.
            template_type: One of VALID_TEMPLATE_TYPES.
            data: CardObject dict populating the card. Provide either ``data``
                or ``data_url``.
            data_url: URL that provides data to the card. Provide either
                ``data`` or ``data_url``.
            roles: Optional list of authorized roles.
            drilldown_url: Optional "View details" URL.
            description: Optional description, 200 characters or less.
            service_defined_id: Optional service-defined identifier.
            window_open_target: Optional target window for navigation.
            refresh_rate: Optional refresh interval in seconds.

        Returns:
            dict: The parsed API response.
        """
        if not key:
            raise ValueError("key is required")
        if not permissions:
            raise ValueError("permissions must contain at least one permission")
        if data is None and data_url is None:
            raise ValueError("provide either data or data_url")

        self._validate_card_fields(order, title, template_type, description)

        payload = self._prune(
            {
                "permissions": list(permissions),
                "order": int(order),
                "title": title,
                "template_type": template_type,
                "data": data,
                "data_url": data_url,
                "roles": list(roles) if roles else None,
                "drilldown_url": drilldown_url,
                "description": description,
                "service_defined_id": service_defined_id,
                "window_open_target": window_open_target,
                "refresh_rate": refresh_rate,
            }
        )

        return self._request("PUT", key=key, json_body=payload)

    def update_card(
        self,
        key,
        permissions=None,
        roles=None,
        order=None,
        title=None,
        template_type=None,
        data=None,
        data_url=None,
        drilldown_url=None,
        description=None,
        service_defined_id=None,
        window_open_target="_blank",
        refresh_rate=None,
    ):
        """Update fields on an existing card. Only supplied fields are sent.

        PATCH /zen-data/v1/custom_cards/{key}

        Args:
            key: Name of the card to update.
            (remaining args): Same semantics as create_or_replace_card; all
                optional. Omitted (None) fields are not sent.

        Returns:
            dict: The parsed API response.
        """
        if not key:
            raise ValueError("key is required")

        self._validate_card_fields(order, title, template_type, description)

        payload = self._prune(
            {
                "permissions": list(permissions) if permissions else None,
                "roles": list(roles) if roles else None,
                "order": int(order) if order is not None else None,
                "title": title,
                "template_type": template_type,
                "data": data,
                "data_url": data_url,
                "drilldown_url": drilldown_url,
                "description": description,
                "service_defined_id": service_defined_id,
                "window_open_target": window_open_target,
                "refresh_rate": refresh_rate,
            }
        )

        if not payload:
            raise ValueError("update_card requires at least one field to update")

        return self._request("PATCH", key=key, json_body=payload)

    def delete_card(self, key):
        """Delete the custom card with the specified key.

        DELETE /zen-data/v1/custom_cards/{key}

        Args:
            key: Name of the card to delete.

        Returns:
            dict: The parsed API response.
        """
        if not key:
            raise ValueError("key is required")
        return self._request("DELETE", key=key)

    # ------------------------------------------------------------------
    # Card data builders
    #
    # Convenience helpers that build the ``data`` CardObject for each
    # template_type so callers don't have to remember the nested structure.
    # ------------------------------------------------------------------
    @staticmethod
    def build_big_number_data(
        metric, sub_text, prefix=None, suffix=None, footer_1=None, footer_2=None
    ):
        """Build a CardObject for the ``big_number`` template."""
        return {
            "big_number_data": SoftwareHubCustomCardManager._prune(
                {
                    "metric": str(metric),
                    "sub_text": sub_text,
                    "prefix": prefix,
                    "suffix": suffix,
                    "footer_1": footer_1,
                    "footer_2": footer_2,
                }
            )
        }

    @staticmethod
    def build_donut_data(data_array, center_label):
        """Build a CardObject for the ``donut`` template.

        Args:
            data_array: List of {"group": str, "value": number} dicts.
            center_label: Label displayed in the center of the donut.
        """
        return {
            "donut_data": {
                "data_array": list(data_array),
                "center_label": center_label,
            }
        }

    @staticmethod
    def build_bar_data(data_array, x_axis_label, y_axis_label):
        """Build a CardObject for the ``bar`` template.

        Args:
            data_array: List of {"group": str, "value": number} dicts.
            x_axis_label: X axis label.
            y_axis_label: Y axis label.
        """
        return {
            "bar_data": {
                "data_array": list(data_array),
                "x_axis_label": x_axis_label,
                "y_axis_label": y_axis_label,
            }
        }

    @staticmethod
    def build_list_data(rows, headers):
        """Build a CardObject for the ``list`` template.

        Args:
            rows: List of table row objects.
            headers: List of table header strings.
        """
        return {
            "list_data": {
                "rows": list(rows),
                "headers": list(headers),
            }
        }

    @staticmethod
    def build_number_list_data(rows):
        """Build a CardObject for the ``number_list`` template.

        Args:
            rows: List of dicts with keys ``label``, ``value`` and optional
                ``drilldown_url``.
        """
        return {"number_list_data": {"rows": list(rows)}}

    @staticmethod
    def build_text_list_data(rows):
        """Build a CardObject for the ``text_list`` template.

        Args:
            rows: List of dicts with keys ``label``, ``sub_text`` and optional
                ``drilldown_url``.
        """
        return {"text_list_data": {"rows": list(rows)}}

    @staticmethod
    def build_content_block_data(rows):
        """Build a CardObject for the ``content_block`` template.

        Args:
            rows: List of dicts with keys ``type`` ("text" or "link"),
                ``content`` and optional ``nav_url`` / ``window_open_target``.
        """
        return {"content_block_data": {"rows": list(rows)}}


# ======================================================================
# Usage examples
#
# The snippets below are intentionally commented out - they document how
# to use this module rather than running on import. Copy what you need
# into your own script and fill in real connection details.
#
# All examples share a single manager. Self-signed clusters typically
# need verify=False, mirroring the docs' `curl -k` examples.
#
# from softwarehub_custom_card_helpers import SoftwareHubCustomCardManager
#
# manager = SoftwareHubCustomCardManager(
#     cpd_cluster_host="https://cpd.example.com",
#     username="admin",
#     api_key="REPLACE_WITH_ZEN_API_KEY",
#     verify=False,
# )
#
# --- big_number: highlights a single significant metric -------------
# data = manager.build_big_number_data(
#     metric="55",
#     sub_text="Increase since last month",
#     prefix="ArrowUp32",          # carbon icon
#     suffix="%",
#     footer_1="867 Total vulnerabilities",
#     footer_2="AskPQL 2.3 package most at risk",
# )
# manager.create_or_replace_card(
#     key="os_vulnerabilities",
#     permissions=["manage_catalog"],
#     order=1,
#     title="Open source vulnerabilities",
#     template_type="big_number",
#     data=data,
#     drilldown_url="/zen/#/openSource/vulnerabilities",
# )
#
# --- donut: values rendered as percentages in a donut chart ---------
# data = manager.build_donut_data(
#     data_array=[
#         {"group": "Used", "value": 72},
#         {"group": "Free", "value": 28},
#     ],
#     center_label="Disk usage",
# )
# manager.create_or_replace_card(
#     key="disk_usage_donut",
#     permissions=["manage_catalog"],
#     order=2,
#     title="Disk usage",
#     template_type="donut",
#     data=data,
# )
#
# --- bar: a two-dimensional bar graph -------------------------------
# data = manager.build_bar_data(
#     data_array=[
#         {"group": "Jan", "value": 12},
#         {"group": "Feb", "value": 18},
#         {"group": "Mar", "value": 9},
#     ],
#     x_axis_label="Month",
#     y_axis_label="Deployments",
# )
# manager.create_or_replace_card(
#     key="monthly_deployments",
#     permissions=["manage_catalog"],
#     order=3,
#     title="Monthly deployments",
#     template_type="bar",
#     data=data,
# )
#
# --- list: a table of navigation links with headers -----------------
# data = manager.build_list_data(
#     headers=["Service", "Status"],
#     rows=[
#         {"Service": "Data virtualization", "Status": "Running"},
#         {"Service": "Watson Studio", "Status": "Running"},
#     ],
# )
# manager.create_or_replace_card(
#     key="service_status_list",
#     permissions=["manage_catalog"],
#     order=4,
#     title="Service status",
#     template_type="list",
#     data=data,
# )
#
# --- number_list: rows of a big numeric value with a label ----------
# data = manager.build_number_list_data(
#     rows=[
#         {
#             "label": "Total approved packages",
#             "value": "25k",
#             "drilldown_url": "/zen/#/openSource/packages",
#         },
#         {"label": "Pending review", "value": "312"},
#     ]
# )
# manager.create_or_replace_card(
#     key="package_counts",
#     permissions=["manage_catalog"],
#     order=5,
#     title="Package counts",
#     template_type="number_list",
#     data=data,
# )
#
# --- text_list: rows of a label with smaller sub-text ---------------
# data = manager.build_text_list_data(
#     rows=[
#         {
#             "label": "Data virtualization",
#             "sub_text": "Increase since last month",
#             "drilldown_url": "/zen/#/dataVirtualization",
#         },
#         {"label": "Watson Studio", "sub_text": "No change"},
#     ]
# )
# manager.create_or_replace_card(
#     key="service_highlights",
#     permissions=["manage_catalog"],
#     order=6,
#     title="Service highlights",
#     template_type="text_list",
#     data=data,
# )
#
# --- content_block: rows of text paragraphs or clickable links ------
# data = manager.build_content_block_data(
#     rows=[
#         {"type": "text", "content": "Welcome to your Software Hub home page."},
#         {
#             "type": "link",
#             "content": "View the getting started guide",
#             "nav_url": "https://www.ibm.com/docs/cloud-paks/cp-data",
#             "window_open_target": "_blank",
#         },
#     ]
# )
# manager.create_or_replace_card(
#     key="welcome_block",
#     permissions=["manage_catalog"],
#     order=7,
#     title="Welcome",
#     template_type="content_block",
#     data=data,
# )
#
# --- update (PATCH): only the supplied fields are sent --------------
# manager.update_card(key="disk_usage_donut", title="Disk usage (cluster)")
#
# # data_url is an alternative to an inline data object.
# manager.update_card(
#     key="disk_usage_donut",
#     data_url="/v1/homepage/diskUsage",
#     refresh_rate=30,
# )
#
# --- list and delete ------------------------------------------------
# cards = manager.list_cards()
# print(cards)
#
# manager.delete_card(key="welcome_block")
# ======================================================================
