apiVersion: ccs.cpd.ibm.com/v1beta1
kind: CCS
metadata:
  name: ccs-cr
  namespace:  cpd-operands #${PROJECT_CPD_INST_OPERANDS}
spec:
  license:
    accept: true
  non_olm_deploy: true
  blockStorageClass: ocs-storagecluster-ceph-rbd #${STG_CLASS_BLOCK}
  nonOlmDeploy: true
  scaleConfig: small
  imagePullSecret: pull-secret #${IMAGE_PULL_SECRET}
  docker_registry_prefix: icr.io #${IMAGE_PULL_PREFIX}
  version: 13.0.0
  fileStorageClass: ocs-storagecluster-cephfs #${STG_CLASS_FILE}
  storageClass: ocs-storagecluster-cephfs #${STG_CLASS_FILE}